### ISSUE TITLE
Documentation to use by importing in python script is missing

### ISSUE THREAD

**Issue by zain-CSsol** [deepraj1729/yplate#1]
There is no documentation provided to use the yplate by importing it in custom python script so that no need to call command line params, switches or flags

**Comment by deepraj1729** [comment]
Yeah, you need to pass it as params to the functions:
# detect:
        detect(img,cfg,weights,classes,save_img,hide_img,hide_out)

# crop:
        crop(img,cfg,weights,classes,save_img,hide_img,hide_out)

### yplate new version is coming soon with OCR on cropped plates
